# Generated by Django 3.2.5 on 2021-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_quantity', models.IntegerField()),
                ('product_flag', models.CharField(choices=[('Bought', 'Bought'), ('Left', 'Left'), ('Non Available', 'Non Available')], max_length=20)),
                ('product_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
