# Generated by Django 3.2.5 on 2021-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerybag',
            name='product_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grocerybag',
            name='product_flag',
            field=models.CharField(choices=[('Bought', 'BOUGHT'), ('Left', 'LEFT'), ('Not Available', 'NOT AVAILABLE')], max_length=20),
        ),
    ]
