# Generated by Django 3.2.5 on 2021-07-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grocery_app', '0003_alter_grocerybag_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerybag',
            name='product_quantity',
            field=models.CharField(max_length=20),
        ),
    ]
