# Generated by Django 3.2.5 on 2021-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grocery_app', '0004_alter_grocerybag_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerybag',
            name='product_flag',
            field=models.CharField(choices=[('Bought', 'BOUGHT'), ('Pending', 'PENDING'), ('Not Available', 'NOT AVAILABLE')], max_length=20),
        ),
    ]
